InternshipProject-chatbot3/chatbot/urls.py
from django.conf.urls import url
from .views import *
from django.conf.urls import url
from . import views


# app_name = 'app'


urlpatterns = [
    url(r'^$', run_script, name='run_script'),
    # url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^final_response/$', views.final_response, name='final_response'),
]

app/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'app'

urlpatterns= [
    url(r'^$',views.HomeView.as_view(),name='home'),
    url(r'^extract$',views.extract,name='extract'),
]

chatbot/urls.py
from django.conf.urls import url
from .views import *
from django.conf.urls import url
from . import views


# app_name = 'app'


urlpatterns = [
    url(r'^$', run_script, name='run_script'),
    url(r'^final_response/$', views.final_response, name='final_response'),
     url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                views.activate, name='activate'),
]

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from chatbot import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home , name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'login_success/$', core_views.login_success, name='login_success'),
    url(r'^login_success/chatbot/',include("chatbot.urls", namespace="chatbot")),

    url(r'^signup/account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
]

chatbot/models.py
from __future__ import unicode_literals


from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed= models.BooleanField(default=False)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

chatbot/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

InternshipProject-chatbot3/chatbot/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.http.response import JsonResponse
from django.template.loader import render_to_string
from extract import *


params = {}


class HomeView(TemplateView):
    template_name = "app/home.html"


@csrf_exempt
def final_response(request):
    print "in final response"
    action = None
    userInput = None
    chatbotResponse = None
    url = None
    
    if request.method == 'POST' and request.is_ajax():
        if 'action' in request.POST:
            action = request.POST['action']
            if action == "run_script":
                print "action %s" % action
                keys = ["battery", "camera", "company", "max_battery", "max_screen_size", "memory",
                         "min_battery", "min_screen_size", "network", "os", "price_from", "price_to", "ram",
                        "screen_size"]
                parameters = {}
                # global params
                # for key in keys:
                #     value = request.POST["parameters[" + key + "]"]
                #     try:
                #         a = params[key]
                #     except KeyError:
                #         params[key] = value
                # print params
                for key in keys:
                    try:
                        value = request.POST["parameters[" + key + "]"]
                        parameters[key] = value
                    except:
                        continue
                print "params: %s" % parameters
                f = Flip(parameters)
                # f = Flip(params)
                item_list = f.extract()
                # request.session['url'] = url
                # return final_response(request)
                #print "url: %s" % url
                #context={'url_key': url}
                #print context
                #return render(request, "chatbot/display.html", context)
                #return redirect('run_script',url_key=url)
                #return render(request,'chatbot/test.html')
                #return JsonResponse({'url_key':url})

                #return render(request, "chatbot/finalresponse.html",context)
                return render(request,"chatbot/list.html",context = {'item_list':item_list})

    
        

@csrf_exempt
def run_script(request):
    """
    action = None
    userInput = None
    chatbotResponse = None
    url = None
    if request.method == 'POST':
        if 'action' in request.POST:
            action = request.POST['action']
            if action == "run_script":
                print "action %s" % action
                keys = ["battery", "camera", "company", "max_battery", "max_screen_size", "memory",
                         "min_battery", "min_screen_size", "network", "os", "price_from", "price_to", "ram",
                        "screen_size"]
                parameters = {}
                for key in keys:
                    value = request.POST["parameters[" + key + "]"]
                    parameters[key] = value
                f = Flip(parameters)
                url = f.extract()
                request.session['url'] = url
                #return final_response(request)
                print "url: %s" % url
                context={'url_key': url}
                print context
                #return render(request, "chatbot/display.html", context)
                #return redirect('run_script',url_key=url)
                #return render(request,'chatbot/test.html')
                return JsonResponse({'url_key':'url'})
    """
    return render(request, "chatbot/display.html")

chatbot/views.py
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.views.generic import FormView
from website.settings import DEFAULT_FROM_EMAIL
from django.views.decorators.csrf import csrf_exempt
from extract import *
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.encoding import force_text
from .tokens import account_activation_token
from django.contrib.auth.models import User
#from chatbot.forms import SignUpForm
#from .forms import SignUpForm

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, get_user_model
from django.contrib.auth import authenticate
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage, send_mail, EmailMultiAlternatives

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        return redirect('../../../login/')
    else:
        return render(request, 'chatbot/account_activation_invalid.html')
# MAIL SENT FOR ACTIVATION
def account_activation_sent(request):
   return render(request, 'chatbot/activate_mail.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate your blog account.'
            message = render_to_string('account_activation_email.html', {
                'user':user, 'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            # user.email_user(subject, message)
            toemail = form.cleaned_data.get('email')
            email = EmailMessage(subject, message, to=[toemail])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def login_success(request):
    test = request.user.first_name
    test1 = request.user.profile.email_confirmed
    if test1 == True:
        return redirect('chatbot/')
    return render(request, 'chatbot/login_fail.html')

def home(request):
    return render(request, 'home.html')



params = {}


@csrf_exempt
def final_response(request):
    if request.method == 'POST' and request.is_ajax():
        if 'action' in request.POST:
            action = request.POST['action']
            if action == "run_script":
                print "action %s" % action
                keys = ["battery", "camera", "company", "max_battery", "max_screen_size", "memory",
                         "min_battery", "min_screen_size", "network", "os", "price_from", "price_to", "ram",
                        "screen_size"]
                parameters = {}
                for key in keys:
                    try:
                        value = request.POST["parameters[" + key + "]"]
                        parameters[key] = value
                    except:
                        continue
                print "params: %s" % parameters
                f = Flip(parameters)
                item_list = f.extract()
                return render(request,"chatbot/list.html",context = {'item_list':item_list})


@csrf_exempt
def run_script(request):
    return render(request, "chatbot/display.html")

chatbot/templates/chatbot/account_activation_invalid.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invalid Chatbot</title>
    <h1> Account activation invalid or you have already activate the account</h1>

</head>
<body>

</body>
</html>

chatbot/templates/chatbot/activate_mail.html
{% block content %}
<div class="in_center container-fluid">
    <p> The activation link to the mentioned email id has been sent. </p>
    <p>   Please check your email to activate your account.</p>
</div>
{% endblock %}
</body>
</h

chatbot/templates/chatbot/display.html
{% load staticfiles %}
<html>
<head>
  <title>Chatbot</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/style_display.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <script type="text/javascript">

    var accessToken = "b44e27ee73964ceaac278ffdd0d7f32d",
      baseUrl = "https://api.api.ai/v1/",
      $speechInput,
      recognition,
      messageInternalError = "Oh no, there has been an internal server error",
      URL = "{% url 'chatbot:run_script' %}" ,
      chatbotreply = new Array() ,
      userInputArray = new Array(),
      globalParameters = new Object();

    $(document).ready(function() {
      $speechInput = $("#speech");
      $speechInput.keypress(function(event) {
        if (event.which == 13) {
          event.preventDefault();
          send();
        }
      });


      $(".debug__btn").on("click", function() {
        $(this).next().toggleClass("is-active");
        return false;
      });
    }); // end ready

    function startRecognition() {

      recognition.onstart = function(event) {
        respond(messageRecording);
        updateRec();
      };
      recognition.onresult = function(event) {
        recognition.onend = null;

        var text = "";
          for (var i = event.resultIndex; i < event.results.length; ++i) {
            text += event.results[i][0].transcript;
          }
          setInput(text);
        stopRecognition();
      };

    }

    function setInput(text) {
      $speechInput.val(text);
      send();
    }

    function send() {
      var text = $speechInput.val();

      $.ajax({
        type: "POST",
        url: baseUrl + "query",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        headers: {
          "Authorization": "Bearer " + accessToken
        },
        data: JSON.stringify({query: text, lang: "en", sessionId: "yaydevdiner"}),
        success: function(data) {
          prepareResponse(data);
        },
        error: function() {
          respond(messageInternalError);
        }
      });
    }

    function prepareResponse(val) {
      var debugJSON = JSON.stringify(val, undefined, 2),
        spokenResponse = val.result.speech,
        action = val.result.action,
        parameters = val.result.parameters,
        text = $speechInput.val();

        for(var key in parameters){
          if(parameters[key] != "" ){
            globalParameters[key] = parameters[key];
          }
                      
        }
        console.log("parameters: ", globalParameters);
        var data = {'chatbotResponse':spokenResponse, 'action':action,'userInput':text, 'parameters':globalParameters } ;
        $.ajax({
            type: "POST",
            url: '{% url 'chatbot:final_response' %}',
            //url: "/final_response/$",
            //contentType: "application/json; charset=utf-8",
            dataType: "html",
            data: data,
           success: function(data){
              console.log("Yep!");
              console.log(data);
              //document.getElementById("url_key").setAttribute("href",data.url_key);
              document.open();
              document.write(data);
              document.close();
            },

            error: function() {
              console.log("Nope :(");
            },

          });
        $("#speech").val("");
        send_data(data);
        respond(spokenResponse);
        debugRespond(debugJSON);
        chatbotreply.push(spokenResponse);
        userInputArray.push(text);

        chat = document.getElementById('main')

        //user
        var li = document.createElement('li')
        li.setAttribute('class','right clearfix')
        var span = document.createElement('span')
        span.setAttribute('class','chat-img pull-right')
        var img = document.createElement('img')
        img.src = "{% static 'images/user.png' %}"
        img.setAttribute('alt','User Avatar')
        img.setAttribute('class','img-circle')
        img.setAttribute('style','width:50px;height:50px;')
        var div = document.createElement('div')
        div.setAttribute('class',"pull-right chat-body clearfix")
        div.id = 'user'
        var div2 = document.createElement('div')
        div2.setAttribute('class','header')
        var strong = document.createElement('strong')
        strong.setAttribute('class',"primary-font")
        {% if request.user.username %}
        strong.innerHTML = "{{request.user.username}}"
        {% else %}
        strong.innerHTML = "User"
        {% endif %}
        var p = document.createElement('p')
        p.innerHTML = text

        span.appendChild(img)
        div2.appendChild(strong)
        div.appendChild(div2)
        div.appendChild(p)
        li.appendChild(span)
        li.appendChild(div)

        chat.appendChild(li)

        
        //chatbot
        var ch_li = document.createElement('li')
        ch_li.setAttribute('class','left clearfix')
        var ch_span = document.createElement('span')
        ch_span.setAttribute('class','chat-img pull-left')
        var ch_img = document.createElement('img')
        ch_img.src = "{% static 'images/eva-chatbot.png' %}"
        ch_img.setAttribute('alt','Chatbot Avatar')
        ch_img.setAttribute('class','img-circle')
        ch_img.setAttribute('style','width:50px;height:50px;')
        var ch_div = document.createElement('div')
        ch_div.setAttribute('class',"chat-body clearfix")
        ch_div.id = 'chatbot'
        var ch_div2 = document.createElement('div')
        ch_div2.setAttribute('class','header')
        var ch_strong = document.createElement('strong')
        ch_strong.setAttribute('class',"primary-font")
        ch_strong.innerHTML = 'Chatbot'
        var ch_p = document.createElement('p')
        ch_p.innerHTML = spokenResponse

        ch_span.appendChild(ch_img)
        ch_div2.appendChild(ch_strong)
        ch_div.appendChild(ch_div2)
        ch_div.appendChild(ch_p)
        ch_li.appendChild(ch_span)
        ch_li.appendChild(ch_div)

        chat.appendChild(ch_li)

        var mainDiv = document.getElementById('mainDiv')
        
        mainDiv.scrollTop = mainDiv.scrollHeight

            }

    function send_data(data){
       $.post(URL,data,function(response){

        if(response=='success')
            {console.log('success');}
        else{console.log('error');}
       });
    }

    function debugRespond(val) {
      $("#response").text(val);
    }
    function respond(val) {
      if (val == "") {
        val = messageSorry;
      }

      $("#spokenResponse").addClass("is-active").find(".spoken-response__text").html(val);
    }
  </script>


    </head>
<body>

  <link href="https://fonts.googleapis.com/css?family=Titillium+Web:200" rel="stylesheet" type="text/css">

<div class="container">

    <div  class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2 align="center">
                        Shopping Assistant Chatbot
                    </h2>
                </div>
                <div id='mainDiv' class="panel-body">
                    <ul id = 'main' class="chat">

                    </ul>
                </div>
                <div class="panel-footer">
                    <div class="input-group">
                        <input id="speech" type="text" class="form-control input-sm" placeholder="Type your message here...">
                        <span class="input-group-btn">
                            <button class="btn btn-warning btn-sm" id="btn-chat">
                                Send</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--
<div>
<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>
</div>
-->
</body>
</html>

chatbot/templates/chatbot/finalresponse.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>jhingalala hoo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}"/>

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <div class="panel panel-primary">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <ul class="chat">
                        <li class="left clearfix"><span class="chat-img pull-left">
                            <img src="http://placehold.it/50/55C1E7/fff&amp;text=U" alt="User Avatar" class="img-circle">
                        </span>
                            <div class="chat-body clearfix">

                                <p>
                                    <a href="{{url_key}}">
                                        Check out these phones!!
                                    </a>
                                </p>
                            </div>
                        </li>

                    </ul>
                </div>
                <div class="panel-footer">
                    <a href="{% url 'chatbot:run_script' %}">
                        Click here to filter specs and get new results!!
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

chatbot/templates/chatbot/list.html
{% load staticfiles %}

<html>
  <head>
    <title>A list specially for you</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="{% static 'css/style_list.css' %}" />

   </head>
  <body bgcolor="#fff8dc">
{#  <div style="background-color: turquoise">#}
{#      <h2 align="center">#}
        <div class="panel-primary">
            <div class="panel-heading">
                <p class="h3" align="center">
                  Check out these phones!
                </p>
            </div>
            <h3>
                <a href="{% url 'chatbot:run_script' %}" style="float: right ">Go back to Chatbot</a>
            </h3>
        </div>
{#      </h2>#}
{#  </div>#}
<div class="panel-body">
    {% for  item in item_list %}
{#        <div class="boxed">#}

            <div class="col-sm-4 col-lg-3">
                <div class="box">
                <div class="thumbnail">
                    <div class="caption">
                        <a href="#" class="image featured">
                            <img class="my-img" src="{{item.img}}" alt="{{item.name}}">
                        </a>
                    </div>
                </div>

                  <ul style="color:black">
                        {% for spec in item.spec %}
                          <li>{{spec}}</li>
                        {% endfor %}
                  </ul>
                  <a href="{{item.url}}" class="button">
                      Take me there
                  </a>
                </div>
            </div>
        {% empty %}
            <h3>
                No phones to show :(
            </h3>
    {% endfor %}
</div>
  </body>
</html>

chatbot/templates/chatbot/login_fail.html
{% extends 'base2.html' %}
{% block content %}
<div class="in_center container-fluid">
    <p>Please confirm your email by clicking on the link sent to your email.</p>
</div>

{% endblock %}

</body>
</html>